  // Example dictionary
  const dictionary = {
    
  "jeunes": "young",
  "de": "of",
  "francophones": "French speakers",
  "les yeux": "the eyes",
  "cheveux": "hair",
  "aussi": "also",
  "en ligne": "online",
  "surtout": "especially",
  "contre": "against , vs",
  "On": "we( street language )",
  "les jeux vidéo": "video games",
  "assez": "enough",
  "grand , grande": "tall",
  "beaucoup": "a lot",
    "père": "father",
    "une mère": "mother",
    "famille": "family",
    "grand-mère": "grandmother",
    "grand-père": "grandfather",
    "Français": "French",
    "frère": "brother",
    "sœur": "sister",
    "cousin": "cousin",
    "cousine": "cousin (female)",
    "oncle": "uncle",
    "tante": "aunt",
    "garçon": "boy",
    "fille": "girl",
    "enfant": "child",
    "enfante": "child (female)"   ,
  "monde": "world",
  "quoi": "what",
  "pourquoi": "why",
  "qui": "who",
  "comment": "how",
  "où": "where",
  "combien": "how much , how many",
    "quand": "when",
  "depuis quand": "since when , how long",
  "quel": "which"
,  "quel": "which (female)",

  };
